---
    - name: 'Install dependency packages'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - mysql-server-5.7
        - python3-mysqldb

    - name: 'Create database'
      mysql_db:
        name: "{{ wp_db_name}}"
        login_user: root
        state: present
      become: yes

    - name: 'Create user'
      mysql_user:
        name: "{{ wp_username }}"
        password: "{{ wp_user_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: "{{ item }}"
      become: yes
      with_items:
        - "{{ wp_host_ip }}"

    - name: 'Copy MySQL Config'
      copy:
        src: 'files/mysqld.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      become: yes
      notify:
        - restart mysql